<?php

namespace Levi9\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends EntityRepository
{
    //todo: this class is not used. Remove it.
}
