levi9_calendar:
    resource: "@Levi9CalendarBundle"
    type:     annotation
    prefix:   /{_locale}/
    requirements: { _locale: en|ru }

levi9_calendar_redirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true

login:
    path: /{_locale}/login
    defaults: { _controller: Levi9CalendarBundle:Security:login, _locale: en }
    requirements:
        _locale: en|ru
login_check:
    path: /login_check
logout:
    path: /logout