levi9_calendar_homepage:
    resource: "@Levi9CalendarBundle"
    type:     annotation
    # todo: define _locale in "prefix" here or in main routing file. Then you would not need to write _locale stuff in each action

login:
    path: /{_locale}/login
    defaults: { _controller: Levi9CalendarBundle:Security:login, _locale: en }
    requirements:
        _locale: en|ru
login_check:
    path: /login_check
logout:
    path: /logout