levi9_calendar_homepage:
    resource: "@Levi9CalendarBundle"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: en }
    requirements: { _locale: en|ru }

login:
    path: /{_locale}/login
    defaults: { _controller: Levi9CalendarBundle:Security:login, _locale: en }
    requirements:
        _locale: en|ru
login_check:
    path: /login_check
logout:
    path: /logout