parameters:
    levi9_calendar.calendar.class: Levi9\CalendarBundle\Service\Calendar

services:
    levi9_calendar.calendar:
        class: %levi9_calendar.calendar.class%
        arguments: [@doctrine]
