security:
    providers:
        user_db:
            entity:
                class: Levi9\CalendarBundle\Entity\User
                property: username

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout: ~

    access_control:
        - { path: /login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        Levi9\CalendarBundle\Entity\User: plaintext
