security:
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:   /login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
            logout: ~

    access_control:
        - { path: /login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
