security:
    providers:
        user_db:
            entity:
                class: Levi9\CalendarBundle\Entity\User
                property: username

    firewalls:
    # todo: Firewall is something that represents secured area. There is only one secured area in this project.
    # todo: So, remove other. If you need unauthorised access to some files - define this rules in access_control section
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:   /login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_check
            logout: ~

    access_control:
        - { path: /login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        Levi9\CalendarBundle\Entity\User: plaintext
